app/inventory/Models/Book.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace inventory.Models  {
    public class Book  {
        public int ID  {get; set;}
        public String Name { get; set; }
        public int Pages { get; set; }
        public String Author { get; set; }
        public String ImageUrl  {get; set;}
        public double Price  {get; set;}
        public int InStock  {get; set;}
    }    
}

app/inventory/Pages/Claims.cshtml.cs
using System.Collections.Generic;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace inventory.Pages
{
    public class ClaimsModel : PageModel
    {
        public IEnumerable<Claim> UserClaims { get; set; }
        public void OnGet()
        {
            UserClaims = HttpContext.User.Claims;
        }
    }
}   

app/inventory/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using inventory.Data;
using inventory.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace inventory.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly BookContext _context;

        public IndexModel(ILogger<IndexModel> logger, BookContext context)
        {
            _logger = logger;
            _context=context;
        }

        public void OnGet()
        {
            List<Book> books=null;
            
            try  {
                books=_context.Books.ToList();
            }
            catch (Exception ex)  {
                ViewData["Error"]=ex.Message;
            }
            ViewData["books"]=books;

        }

        public IActionResult OnPostSaveInventory()  {
            var bookId=int.Parse(Request.Form["bookId"]);
            var quantity=int.Parse(Request.Form["book.InStock"]);
            var book=_context.Books.Find(bookId);
            book.InStock=quantity;
            _context.SaveChanges();           

            return RedirectToPage();
        }      
    }
}

app/inventory/Pages/Claims.cshtml
@page
@model inventory.Pages.ClaimsModel

<div class="row">
    <div class="col-md-12">
        <table class="table table-responsive table-striped">
            @if (HttpContext.User.Identity.IsAuthenticated)
            {
                foreach (var c in Model.UserClaims)
                {
                    <tr>
                        <td>@c.Type</td>
                        <td>@(c.Value.Length > 100 ? c.Value.Substring(0, 100) : c.Value)</td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td>Current Status</td>
                    <td><strong>Not Authenticated</strong></td>
                </tr>
            }
        </table>
    </div>
</div>

app/inventory/Pages/Index.cshtml
@page

@using Models;

@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-5">Manage Inventory</h1>
    @if (ViewData["books"] != null)
    {
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Author</th>
                <th>Pages</th>
                <th>Price</th>
                <th></th>
            </tr>


            @foreach (var book in ViewData["books"] as List<inventory.Models.Book>)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(m=>book.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(m=>book.Author)
                    </td>
                    <td>
                        @Html.DisplayFor(m=>book.Pages)
                    </td>
                    <td>
                        @Html.DisplayFor(m=>book.Price)
                    </td>
                    <td>
                        <form asp-page-handler="saveInventory" method="post">
                            <input type="hidden" name="bookId" value="@book.ID" />
                            @Html.TextBoxFor(m=>book.InStock)
                            <button>Save</button>
                        </form>
                    </td>
                </tr>
            }
        </table>
    }
    else  {
        <br/>
        <h2 class="display-7">Nothing to see here folks :-)</h2>
    }

    @if (ViewData["Error"]!=null)  {
        <p style='color: red'>@ViewData["Error"]</p>
    }
</div>

app/inventory/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Inventory</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <img width="100" src="~/images/logo.jpg" />
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <H4>Inventory</H4>
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li><a asp-area="" asp-controller="Session" asp-action="EditProfile">Hello @User.Claims.First(c=>c.Type=="name").Value!</a>
                        </li>                        
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>Anonymous User</li>
                    </ul>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ReadIt!
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>

</html>