app/cart/Models/Book.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace cart.Models  {
    public class Book  {
        public int ID  {get; set;}
        public String Name { get; set; }
        public int Pages { get; set; }
        public String Author { get; set; }
        public String ImageUrl  {get; set;}
        public double Price  {get; set;}
        public int InStock  {get; set;}
    }    
}

app/cart/Pages/Index.cshtml.cs
using Azure.Storage.Blobs;
using cart.Data;
using cart.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using ServiceStack.Redis;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace cart.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly BookContext _context;
        private readonly IConfiguration _config;

        public IndexModel(ILogger<IndexModel> logger, IConfiguration config , BookContext context)
        {
            _logger = logger;
            _context=context;   
            _config=config;        
        }

        public void OnGet()
        {

            List<Book> books=new List<Book>();

            // UNCOMMENT AFTER WE HAVE A DATABASE  
            books=GetBooksInShoppingCart();

            ViewData["books"]=books;
        }

        public IActionResult OnPostRemoveFromShoppingCart()  {
            var bookId=int.Parse(Request.Form["bookId"]);
            var book=_context.Books.Find(bookId);
            book.InStock++;
            _context.SaveChanges();
            
            var client=GetRedisClient();
            client.RemoveItemFromList("cart", bookId.ToString());            

            return RedirectToPage();
        }  

        public void OnPostPlaceOrder()  {
            
            var booksInCart=GetBooksInShoppingCart();
            var order=new Order();
            double total=0;
            order.orderDate=DateTime.Now;
            order.items=new List<OrderItem>();

            foreach (var book in booksInCart)  {
                var item=new OrderItem();
                item.name=book.Name;
                item.id=book.ID;
                item.price=book.Price;
                total+=item.price;
                order.items.Add(item);
            }

            order.total=total;

            var json=JsonConvert.SerializeObject(order);

            Console.WriteLine(json);

            try  {
                string storageConnection = _config.GetValue<String>("StorageConnectionString"); 
                var blobService=new BlobServiceClient(storageConnection);
                var container=blobService.GetBlobContainerClient("neworders");
                var blobClient=container.GetBlobClient($"order_{Guid.NewGuid().ToString()}.json");
                
                // Prepare stream for upload
                byte[] byteArray=Encoding.ASCII.GetBytes(json);
                MemoryStream stream=new MemoryStream(byteArray);
                
                var resp=blobClient.Upload(stream); 

                Console.WriteLine("Order sent!");

                ClearCart();                

                ViewData["books"]=new List<Book>();
                ViewData["OrderStatus"]="sent";
            }
            catch (Exception ex)  {
                ViewData["OrderStatus"]="Error sending order: " + ex.Message;
            }
        }      

        public IActionResult OnPostLoad()  {
            BookLoader.LoadBooks(_context);
            return RedirectToPage();
        }

        private List<Book> GetBooksInShoppingCart()  {

            var client=GetRedisClient();
            var bookIDs=client.GetAllItemsFromList("cart");
                 
            return _context.Books.Where(b=>bookIDs.Contains(b.ID.ToString())).ToList();
        }

        private void ClearCart()  {

            var client=GetRedisClient();
            client.RemoveAllFromList("cart");
        }

        private IRedisClient GetRedisClient()
        {
            var conString = _config.GetValue<String>("Redis:ConnectionString");
            var manager = new RedisManagerPool(conString);
            return manager.GetClient();
        }
    }

    class Order  {
        public int orderId  {get; set;}
        public DateTime orderDate  {get; set;}
        public double total { get; set; }
        public List<OrderItem> items { get; set; }

        public Order()
        {
            orderId=new Random().Next(1000);
        }
    }

    class OrderItem  {
        public String name { get; set; }
        public int id { get; set; }
        public double price { get; set; }
    }
}

app/cart/Pages/Index.cshtml
@page

@using Models

@model IndexModel
@{
    ViewData["Title"] = "Home page";
    var books=ViewData["books"] as List<Book>;
}

<div class="text-center">

    <h1 class="display-5">Shopping Cart</h1>
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Author</th>
            <th>Price</th>   
            <th></th>       
        </tr>        
    
    @foreach (var book in books)
    {
        <tr>
            <td>
                @Html.DisplayFor(m=>book.Name)
            </td>
            <td>
                @Html.DisplayFor(m=>book.Author)
            </td>
            <td>
                @Html.DisplayFor(m=>book.Price)
            </td>
            <td>
                <form asp-page-handler="removeFromShoppingCart" method="post">
                    <input type="hidden" name="bookId" value="@book.ID"/>
                    <button>Remove from shopping cart</button>
                </form>                
            </td>
        </tr>        
    }
    </table> 

    @if (books.Count>0)  {
        <form asp-page-handler="placeOrder" method="post">
            <button>Place Order</button>
        </form>
    }   

    @if (ViewData["OrderStatus"]!=null)  {
        <p>@ViewData["OrderStatus"]</p>
    }
</div>

app/cart/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ReadIt! - cart</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <img width="100" src="~/images/logo.jpg"/>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <img width="40" src="~/images/cart.JPG"/>                            
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ReadIt! 
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>